### PR TITLE
ci/cd: Migrate Tern from CircleCI to GH Actions

### LINKED ISSUE #492: Use GitHub Actions for Tern's CI/CD pipeline
**Describe the Feature**
Utilize GitHub actions for Tern's CI/CD pipeline. This will replace the current CircleCI continuous integration.

**Use Cases**
For opening pull requests

**Implementation Changes**
1) Create a new directory `tern/.github/workflows/main.yml`
2) Translate Tern's exisiting circleci yaml file to the new GitHub Actions yaml file.

### PR DESCRIPTION
**Pull request by rnjudge**
This commit translates the current lint/test suite from the circleci
yaml file to a new yaml file that will be run by GitHub actions.

Fixes #492

Signed-off-by: Rose Judge <rjudge@vmware.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
If you want to see the potential for what this output might look like when run in Tern's repo, you can look [here](https://github.com/rnjudge/tern/pull/2/checks?check_run_id=444857201). 

Also note that this PR takes in to account pending changes to the circleci config file in PR #530  so we may want to wait to merge this until #531 is resolved and merged.

**Comment by nishakm** [comment]
> Also note that this PR takes in to account pending changes to the circleci config file in PR #530 so we may want to wait to merge this until #531 is resolved and merged.

https://github.com/vmware/tern/pull/531 might take a bit. Any chance of detaching this PR from it?

**Comment by PrajwalM2212** [comment]
@nishakm @rnjudge I have fixed all from my side at https://github.com/vmware/tern/pull/537, https://github.com/vmware/tern/pull/536 and https://github.com/vmware/tern/pull/530

**Comment by nishakm** [comment]
OK, merging this :)

**Pull request merged**
