### PR TITLE
Increase prospect code checking

### PR DESCRIPTION
**Pull request by mkrohan**
Added the ".prospector.yaml" file to control the checks (and their
strictness) performed by prospector.  With the increased strictness,
new code style issues were raised by prospector, most of which are
resolved with this commit.  The issues that need more attention are:

    tern/__main__.py
      Line: 53
        pyflakes: F821 / undefined name 'ModuleNotFoundError' (col 12)

    tern/classes/docker_image.py
      Line: 102
        pep8: N805 / first argument of a method should be named 'self' (col 9)

There is currently a bug with prospector loading of the "pylint" tool
which generates the message

    .
      Line: None
        pylint: failure / Tool pylint failed to run (exception was raised)

This can ignored and will be resolved with a future version.

The stricter prospector report is:

    $ prospector tern/
    Messages
    ========

    .
      Line: None
        pylint: failure / Tool pylint failed to run (exception was raised)

    tern/__main__.py
      Line: 53
        pyflakes: F821 / undefined name 'ModuleNotFoundError' (col 12)

    tern/classes/docker_image.py
      Line: 102
        pep8: N805 / first argument of a method should be named 'self' (col 9)

    tern/classes/image_layer.py
      Line: 107
        pep8: E126 / continuation line over-indented for hanging indent
            (col 24)

    tern/utils/container.py
      Line: 68
        pep8: E128 / continuation line under-indented for visual indent (col 9)

    Check Information
    =================
             Started: 2019-07-08 09:56:51.909231
            Finished: 2019-07-08 09:56:57.221118
          Time Taken: 5.31 seconds
           Formatter: grouped
            Profiles: .prospector.yaml, full_pep8, no_test_warnings,
                      strictness_medium, strictness_high, strictness_veryhigh,
                      no_doc_warnings, no_member_warnings
          Strictness: from profile
      Libraries Used:
           Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
      Messages Found: 5

Signed-off-by: Michael Rohan <mrohan@vmware.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
Hi @mkrohan, thanks for your commit and work to improve prospector in tern.

I noticed that the commit message check is failing due to some lines in the commit message exceeding the recommended value. I know this is really small, but we are trying to wrap all commit message lines at 72 characters -- more info on that here [here](https://github.com/vmware/tern/blob/master/CONTRIBUTING.md#commit-message-format). Would you be so kind as to amend your commit? There's a handful of them that exceed 72 due to the space before the text starts. Specifically:

```
Line:         pep8: N805 / first argument of a method should be named 'self' (col 9)
Line:         pylint: failure / Tool pylint failed to run (exception was raised)
Line:         pylint: failure / Tool pylint failed to run (exception was raised)
Line:         pep8: N805 / first argument of a method should be named 'self' (col 9)
Line:         pep8: E128 / continuation line under-indented for visual indent (col 9)
Line:                       strictness_medium, strictness_high, strictness_veryhigh,
Line:            Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
```

The linting circleci check can be be ignored for now given that the `pylint: failure / Tool pylint failed to run (exception was raised)` error is expected.


Thanks again for your contribution! It is much appreciated :)

**Comment by mkrohan** [comment]
Sure, no problem.

**Comment by mkrohan** [comment]
Updated the commit message.

**Comment by nishakm** [comment]
@mkrohan Your commit message has a weird header
```
         1         2         3         4         5         6         7
12345678901234567890123456789012345678901234567890123456789012345678901234567890
```
Can you get rid of it?

I'll check on the linting error.

**Comment by nishakm** [comment]
> I'll check on the linting error.

Oh oops. The linting error is from the prospector bug. I don't think we can merge this as our linting checks will fail for any subsequent PRs. I think we should hold of until the bug in prospector is resolved.

@mkrohan do you happen to have a link to the issue handy so we can watch it?

**Comment by mkrohan** [comment]
Updated the commit message!  Will do a follow on to update the version of prospector, 1.1.7 is now available.

**Comment by nishakm** [comment]
@mkrohan I've merged a PR that will pin requirements to just the minor version. This should pull prospector version 1.1.7. So your change to dev-requirements.txt shouldn't be needed. Can you update your commit message to not include that change? Thanks again!

**Comment by nishakm** [comment]
closing this as an updated prospector config was merged in #516.

**Pull request closed without merging**
