### PR TITLE
test_class_docker_image: Add a test image

### PR DESCRIPTION
**Pull request by PrajwalM2212**
This PR uses a test docker image to fix the tests
The test docker image has a simple structure
documents
 --test
   --file1.txt
   --file2.txt
   --test2
     --file1.txt
     --file2.txt

Signed-off-by: PrajwalM2212 <prajwalmmath@gmail.com>

### CODE REVIEW

**Comment by rnjudge** [comment]
Just an FYI, when I run this test in my python virtual environment, the test succeeds but I get the warning:

```(tt) rjudge:tern$ python tests/test_class_docker_image.py
./home/rjudge/tt/tern/tern/analyze/docker/container.py:41: ResourceWarning: unclosed
 <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=2049, proto=0, raddr=/var
/run/docker.sock>
  client = docker.from_env()
/home/rjudge/tt/tern/tern/analyze/docker/container.py:41: ResourceWarning: unclosed
 <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=2049, proto=0, raddr=/var
/run/docker.sock>
  client = docker.from_env()
[sudo] password for rjudge: 
./home/rjudge/tt/tern/tern/analyze/docker/container.py:41: ResourceWarning: unclosed
 <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=2049, proto=0, raddr=/var
/run/docker.sock>
  client = docker.from_env()
/home/rjudge/tt/tern/tern/analyze/docker/container.py:41: ResourceWarning: unclosed
 <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=2049, proto=0, raddr=/var
/run/docker.sock>
  client = docker.from_env()
/home/rjudge/tt/tern/tern/analyze/docker/container.py:41: ResourceWarning: unclosed
 <socket.socket fd=6, family=AddressFamily.AF_UNIX, type=2049, proto=0, raddr=/var
/run/docker.sock>
  client = docker.from_env()
..
----------------------------------------------------------------------
Ran 4 tests in 68.366s

OK
sys:1: ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_UNIX,
 type=2049, proto=0, raddr=/var/run/docker.sock>
sys:1: ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_UNIX,
 type=2049, proto=0, raddr=/var/run/docker.sock>
sys:1: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_UNIX,
 type=2049, proto=0, raddr=/var/run/docker.sock>
```

This is just a warning and is not an issue with the test, rather, a symptom of resource handling in `tern/analyze/docker/container.py.` Therefore, this PR looks good to me pending the line length edits mentioned above. Nice work @PrajwalM2212! We have been talking about this for a long time!

**Comment by nishakm** [comment]
@rnjudge Are we good to merge this?

**Comment by PrajwalM2212** [comment]
@rnjudge Done.  The present coverage is 63%. We should probably open a issue to increase test coverage.

**Comment by rnjudge** [comment]
Thanks for the update @PrajwalM2212! Merging this.

**Pull request merged**
