### PR TITLE
Add openjdk:8 to base.yml.  openjdk:8 is based on Debian

### LINKED ISSUE #18: KeyError: openjdk:8
I am getting this error.   Where should I look to get more info on whats happening?

Thanks, Steve

```
2018-03-13 15:47:37,642 - ternlog - DEBUG - Starting...
2018-03-13 15:47:37,642 - ternlog - DEBUG - Creating Report...
2018-03-13 15:47:37,642 - ternlog - DEBUG - Creating a detailed report on components in Docker image...
2018-03-13 15:47:37,644 - ternlog - DEBUG - Running command: sudo docker images openjdk:8
2018-03-13 15:47:37,920 - ternlog - DEBUG - Running command: sudo docker save openjdk:8
2018-03-13 15:48:36,594 - ternlog - DEBUG - Nothing in cache for layer a64142d97d. Invoking from command library
2018-03-13 15:48:36,594 - ternlog - DEBUG - Running command: sudo docker ps -a --filter name=tern-container
2018-03-13 15:48:36,740 - ternlog - DEBUG - Running command: sudo docker run -td --name tern-container openjdk:8
2018-03-13 15:48:39,968 - ternlog - WARNING - No listing of openjdk:8 in the command library. To add one, make an
entry in command_lib/base.yml
2018-03-13 15:48:39,969 - ternlog - DEBUG - Running command: sudo docker ps -a --filter name=tern-container
2018-03-13 15:48:40,172 - ternlog - DEBUG - Running command: sudo docker stop tern-container
2018-03-13 15:48:41,428 - ternlog - DEBUG - Running command: sudo docker rm tern-container
2018-03-13 15:48:44,839 - ternlog - DEBUG - Running command: sudo docker images openjdk:8
2018-03-13 15:48:45,232 - ternlog - DEBUG - Running command: sudo docker rmi -f openjdk:8
2018-03-13 15:48:45,570 - ternlog - DEBUG - Running command: sudo docker images tern-image:1520977657
2018-03-13 15:48:45,951 - ternlog - DEBUG - Running command: sudo docker build -t tern-image:1520977657 -f Dockerfile .
Traceback (most recent call last):
  File "./tern", line 87, in <module>
    main(args, logger)
  File "./tern", line 34, in main
    report.execute(args)
  File "/root/ternenv/tern/report.py", line 280, in execute
    shell = common.get_image_shell(base_image_msg[0])
  File "/root/ternenv/tern/common.py", line 92, in get_image_shell
    'base'][base_image_tag[0]]['tags'][base_image_tag[1]]['shell']
KeyError: 'openjdk'
```

Here is the Dockerfile

```
FROM openjdk:8
EXPOSE 8080
ENV DBHome /opt/deployhub
ENV DBUserName  postgres
ENV DBPassword  postgres
ENV DBConnectionString jdbc:postgresql://dh-db.gotdns.com:5432/postgres
ENV DBDriverName org.postgresql.Driver

RUN mkdir /opt/deployhub
RUN mkdir /opt/deployhub/engine
RUN apt-get update
RUN apt-get -y install net-tools
ADD webapp-runner.jar /opt/deployhub
ADD dh-ms-general.war /opt/deployhub
CMD java -jar /opt/deployhub/webapp-runner.jar --path /dmadminweb /opt/deployhub/dh-ms-general.war 2>&1
```

### PR DESCRIPTION
**Pull request by sbtaylor15**
Added and tested openjdk:8 in command_lib/base.yml.  Resolved #18 with this update.

### CODE REVIEW

**Comment by nishakm** [comment]
Hi @sbtaylor15,
Thanks for your PR! If you don't mind, can you test your listing using the verify_invoke.py script?
This doc should be able to help: https://github.com/vmware/tern/blob/master/docs/adding-to-command-library.md. This should ensure that you are retrieving what you expect.

If you are having trouble with the doc, let me know.

**Comment by sbtaylor15** [comment]
I couldn't find any doc on the verify_invoke.py script.  Looked at the code and came up with this:

 python3 verify_invoke.py  --container distracted_jennings --keys 'openjdk:8' --shell /bin/bash --package perl

I get:

```
Traceback (most recent call last):
  File "verify_invoke.py", line 53, in <module>
    info_dict = look_up_lib(args.keys)
  File "verify_invoke.py", line 22, in look_up_lib
    subd = cmds.command_lib[keys.pop(0)]
KeyError: 'openjdk:8'
```

What am I missing?

Thanks, Steve

**Comment by nishakm** [comment]
Try:
python3 verify_invoke.py --container distracted_jennings --keys base openjdk tags 8 names --shell /bin/bash --package perl

Apologies about the doc: it looks like I didn't add stuff about verify_invoke.py

**Comment by nishakm** [comment]
Hi @sbtaylor15, you seem to have two commits - one has a DCO and the other one does not. Can you remove the first one?

**Pull request closed without merging**
