### PR TITLE
ci: Remove bandit from circleci

### LINKED ISSUE #321: Remove bandit from circleci
**Description**
We had initially enabled Bandit in circleci when we thought that Prospector was interfering with running circleci properly. Now that Prospector and circleci are running in harmony we can disable Bandit from running for each PR.

**To Do**
In .circleci/config.yml. 
1) Remove the 'security' job:
#security linting using Bandit
 security:
   executor: ubuntu1604
   steps to run Bandit
   steps:
     - setup
     - run: pip install -r dev-requirements.txt
     - run: bandit -r .
2) Remove the workflow named 'security' under the jobs list.

**Background**
See description.

**Super Issues**
None

### PR DESCRIPTION
**Pull request by manaswinidas**
Disable bandit from circleci since Prospector and circleci are running in harmony
Resolves #321

### CODE REVIEW

**Comment by rnjudge** [comment]
Hi again, @manaswinidas!

Thanks for your PR and great commit message!

Although your PR removed the 'security' job from .circleci/config.yml, you'll notice that circleci is still trying to run the 'security' job. From the error message:
```
# Error calling workflow: 'PRs'
# Cannot find a definition for job named security
```

Take a look at the jobs that are still listed under the 'workflows' section of config.yml. Do you notice anything there that might be causing the circleci check to fail for this PR?

**Comment by rnjudge** [comment]
Hi @manaswinidas 

One more thing brought to my attention by @nishakm -- it looks like the commit message body for this PR is longer than 72 characters. Could you also amend your commit message body to comply with the Tern commit message [style guidelines](https://github.com/vmware/tern/blob/master/CONTRIBUTING.md#commit-message-format)?

Thanks again!

**Comment by manaswinidas** [comment]
@rnjudge thanks for pointing out. There is still a linting error, is it because of the commit-message again :sweat_smile: ?

**Comment by rnjudge** [comment]
> @rnjudge thanks for pointing out. There is still a linting error, is it because of the commit-message again 😅 ?

The linting error is due to the fact that a PR was merged during the time between your original PR and your updated PR. However, don't worry about fixing this right now as we've decided to hold off on this change related to Bandit for the time being. Thanks for submitting though, we really do appreciate it! 

In the meantime, feel free to take a look at other open issues in the and let me or @nishakm if you have any questions.

**Pull request closed without merging**
