### PR TITLE
Update dockerfile.py with raw string notation

### PR DESCRIPTION
**Pull request by kdmcguire**
Line 32 - added R before string, removed # noqa

For issue #224 (Replace regex strings with raw strings)

### CODE REVIEW

**Comment by rnjudge** [comment]
> Line 32 - added R before string, removed # noqa
> 
> For issue #224

Thanks for your commit and interest in Tern, @kdmcguire! In order to consider merging this commit, could you please amend your commit message with your DCO? VMware requires this for any contributors to Tern. More info and a good example on how to do that [here](https://github.com/vmware/tern/blob/master/CONTRIBUTING.md).

Additionally could you please provide a little more explanation as to your reasoning for submitting this change? Was there a particular issue or environment you noticed that this change was required? 

Thanks again for your interest and commit. Please don't hesitate to reach out should you have any questions.

**Comment by kdmcguire** [comment]
Hey @rnjudge - apologies, I think I've added the required info now.

**Comment by rnjudge** [comment]
> Hey @rnjudge - apologies, I think I've added the required info now.

Hi @kdmcguire -- the DCO bot is still complaining because it wants a real email for the commit instead of the github default. Do you have another email option to use other than `2109807+kdmcguire@users.noreply.github.com`? In order to update it in your commit you can run:

 ```
# git commit --amend --author="Kieran McGuire <real.email@email.com>"
# git commit amend
<When the editor pops up, edit the email in the commit message to match
the email you provided for the author field above.>
```
To avoid this step in the future you can setup your gitconfig according to the directions [here](https://github.com/nishakm/puns#how-to-configure-your-git).

Once the dco is sorted out there are just a few more small changes to make in the commit message:
1) Add what issue this commit addresses. I think your first commit message had this information and it got lost when you force pushed changes. You can add the following above your "signed-off by" dco: `Resolves #224` See an example of what this looks like under the "Commit Message Formats" section [here](https://github.com/vmware/tern/blob/master/CONTRIBUTING.md).

2) You can remove the reference to "Line 32" in your commit message. Thanks to GitHub, the commit itself will show which line number the changes occurred at.

3) Please update the commit message body with a little more information as to why you are making this change. This can be a simple summary like "Replace regex strings with raw strings in  tern/utils/dockerfile.py"

Thanks for your patience with this commit prcoess! You are well on your way to your first commit to Tern and it only gets easier from here! :)

**Comment by kdmcguire** [comment]
Hey @rnjudge, thank you for your patience! I've added my own email address to the sign-off but the clabot still added a comment about it. What've I missed this time?

**Comment by nishakm** [comment]
Hi @kdmcguire, thanks so much for sticking with us! You don't have a `-` in your Signed-off-by:
```

**Comment by kdmcguire** [comment]
@nishakm ha, got it.

There were no issues with the bandit check, but prospector found issues _with other files_ - although the same messages were given before I made the change. Are there any other tests needed for this?

**Comment by nishakm** [comment]
@kdmcguire, granted, prospector is a little iffy with reporting linting and our CI only lints the files that were changed by a PR. I will check it out. Meanwhile, everything looks good for this PR, so I will merge it. Congrats and thanks again for working through it!

**Pull request merged**
