### PR TITLE
90 Add to_dict to DockerImage class

### PR DESCRIPTION
**Pull request by TileThePlane**
Add to_dict method to DockerImage class

This method returns a python dictionary representation of the DockerImage and the derived Image class.

Resolves: #90
See also: #87 

Signed-off-by: TileThePlane kvonderw@uci.edu

### CODE REVIEW

**Comment by TileThePlane** [comment]
@nishakm I have squashed the two previous commits and revised for the message limit. Thanks for reviewing!

**Comment by nishakm** [comment]
@TileThePlane I cannot merge this until you fix the author of your git commit to match the email in your Signed-off-by:
```
commit 4cc868c5d3fbc086123b6c39a721c3f3de676a18 (HEAD -> TileThePlane-90-Add-to-dict)
Author: Kyle <kvonderw@uci.edu> <-- author part
Date:   Mon Oct 1 03:21:11 2018 -0700

    90 Add to_dict to docker_image.py
    
    Add to_dict, DockerImage
    
    Signed-off-by: TileThePlane kvonderw@uci.edu <-- Signed-off-by does not match Author

```
You can changes your Signed-off-by and update your PR.

Otherwise, the code works. Thanks for working on this issue!

**Comment by nishakm** [comment]
@TileThePlane if you want to update the Author of the commit you can do `git commit --amend --author="Your Name <your@email.com>"`

The string "Your Name <your@email.com>" should match your Signed-off-by. Then the dco-required label will go away. I hope this helps

**Comment by nishakm** [comment]
@TileThePlane your Signed-off-by email needs to be in `< >`
```
commit f216779d1295d5f39baa201c9520afc4cbd5e430
Author: Kyle <kvonderw@uci.edu>
Date:   Mon Oct 1 03:21:11 2018 -0700

    90 Add to_dict to docker_image.py
    
    Add to_dict, DockerImage
    
    Signed-off-by: Kyle kvonderw@uci.edu <--- needs to be <kvonderw@uci.edu>
```
Have you setup your gitconfig yet? See here: https://github.com/nishakm/puns#how-to-configure-your-git

**Comment by TileThePlane** [comment]
@nishakm The dco-required label is now removed. Thanks for your patience. I appreciate your opening an issue for a good first PR. Cheers!

**Comment by nishakm** [comment]
@TileThePlane Thank you! It looks good to me 👍 Contribute here anytime!

**Pull request merged**
