### PR TITLE
Preserve newline characters in Dockerfile.lock

### PR DESCRIPTION
**Pull request by mukultaneja**
This PR does following,

1. It includes New lines in Dockerfile lock command and
make the resulting locked dockerfile look cleaner

Resolved: #596

Signed-off-by: mukultaneja <mtaneja@vmware.com>

### CODE REVIEW

**Comment by mukultaneja** [comment]
@nishakm, I looked into `DockerfileParser` object and found that parser itself boils down all the `\n` characters found into the content to `1` at the end. So I added a logic to compute `\n` characters between `Dockerfile` commands through `startline` and `endline` and finally adding it to resulting string.

**Comment by rnjudge** [comment]
Hi @mukultaneja Thanks for your commit! I don't think we want this functionality to live in the "expand_add_command" function as the purpose of that function is to expand `ADD` arguments. Can you move this functionality to it's own function (with `dfobj` as an input parameter) OR add the functionality you wrote to the `create_locked_dockerfile` function in dockerfile.py? 

One other small ask, can you update your commit message title to describe what the commit is doing instead of listing the bug that it is fixing? When people are looking through the commit log we don't want to force them to cross-reference GitHub issues :) Thank you!

**Comment by mukultaneja** [comment]
Hi @rnjudge, thanks for the review. I will definitely change the title of this PR and I think I have only made changes in `create_locked_dockerfile` function itself to get the resultant string at the end.

**Comment by rnjudge** [comment]
@mukultaneja I think `Add ‘checksum’ properties to Image and ImageLayer ` commit accidentally got pushed to this PR.

**Comment by mukultaneja** [comment]
@rnjudge Done!

**Comment by rnjudge** [comment]
I tested this PR and got the following output for `Dockerfile.lock file` which matches the newline characters in the original Dockerfile.

```
# Copyright (c) 2019 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-2-Clause

FROM photon@sha256:e8e0fe89398f41e76f567271fe19b4d0ccf7e7e56ff967cab40902adefcec8de

# install system dependencies
# photon:3.0 comes with toybox which conflicts with some dependencies needed for tern to work, so uninstalling
# toybox first
RUN tdnf remove -y toybox && tdnf install -y tar-1.30-4.ph3 findutils-4.6.0-5.ph3 attr-2.4.48-1.ph3 util-linux-2.32-1.ph3 python3-3.7.5-2.ph3 python3-pip-3.7.5-2.ph3 python3-setuptools-3.7.5-2.ph3 git-2.23.1-2.ph3

# install pip and tern
RUN pip3 install --upgrade pip && pip3 install tern

# make a mounting directory
RUN mkdir hostmount

ENTRYPOINT ["tern", "-q", "-b", "/hostmount"]
CMD ["-h"]
```

**Comment by rnjudge** [comment]
I asked Mukul to add a comment to this commit for clarity. Once he does I think this looks good to merge. @nishakm?

**Comment by mukultaneja** [comment]
@rnjudge Done!

**Pull request merged**
