### PR TITLE
test_class_docker_image.py: Add a test image

### LINKED ISSUE #405: Fix DockerImage class unit tests
**Problem Statement**
The import statements on test files are wrong and need to be rearranged.

**Describe the Proposal**
Describe the change you would like to see in the project.
https://github.com/vmware/tern/blob/master/tests/test_class_docker_image.py
uses 
```python
from classes.docker_image import DockerImage
from utils.container import docker_command
from utils.container import pull
from utils.container import check_image
```
but 
https://github.com/vmware/tern/commit/8092d0fde3059de9115ae485fd7d09cf67642e22 along with a number of PR's had made refactors a lot of code making these import statements outdated. 
This has to be fixed for the tests to run

**Steps to Implement Proposal**
Refactor the import statements in the test files.

### PR DESCRIPTION
**Pull request by PrajwalM2212**
This PR adds a test docker image to fix the tests.
This test docker image has a simple directory
structure as suggested in
#405

Closes #405

Signed-off-by: PrajwalM2212 prajwalmmath@gmail.com

### CODE REVIEW

**Comment by PrajwalM2212** [comment]
@nishakm @rnjudge I have created a test docker image using the file structure you had suggested. I am currently using my account for testing.
I cannot push docker image to `vmware/tern/` repository. I think I should be added as a collaborator to push to be able to push to `vmware/tern/` or one of you should push it.  
I will create another test image for  `vmware/tern/` after we figure out the pushing issue.
After that we can fix up the remaining two failing test classes as well.

**Comment by nishakm** [comment]
@PrajwalM2212 sorry for the delay. Is it OK with you if I push your image to the vmware/tern repo and then you can change the tests to use that image?

**Comment by PrajwalM2212** [comment]
@nishakm Yes, you can push the image.

**Comment by rnjudge** [comment]
@PrajwalM2212 I uploaded your test image to vmware/tern [dockerhub](https://hub.docker.com/r/vmware/tern/tags) with the tag `testimage`. You can update your PR to reference this now :)

Thank you!

**Comment by PrajwalM2212** [comment]
@nishakm @rnjudge I have deleted `tests/test_util_commands.py` and `tests/test_util_metadata.py`. 

`util/commands` does not exist, so we may not need test file for this.

`util/metadata` has one test function called `clean_temp` which is not used anywhere. All cleaning functions are present in `report.py`. Do we need `util/metadata` or should I delete that as well.

**Comment by nishakm** [comment]
> @nishakm @rnjudge I have deleted `tests/test_util_commands.py` and `tests/test_util_metadata.py`.
> 
> `util/commands` does not exist, so we may not need test file for this.
> 
> `util/metadata` has one test function called `clean_temp` which is not used anywhere. All cleanup functions used are present in `report.py`. Do we need `util/metadata` or should I delete that as well.

@PrajwalM2212 I was just going to get rid of those two. Can you delete them in a separate commit?

Could you describe the directory structure in your tarball in the commit message rather than linking it to the issue?

Thanks much!

**Pull request closed without merging**
